"""
email_service.py
────────────────
SendGrid email delivery for completed research reports.
"""

import logging
import markdown as md_lib

from deep_research.core.config import settings

logger = logging.getLogger(__name__)

_HTML_WRAPPER = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body  {{ font-family: Georgia, serif; max-width: 800px; margin: 40px auto;
             padding: 0 20px; color: #222; line-height: 1.7; }}
    h1   {{ color: #1a1a2e; border-bottom: 2px solid #e8e8e8; padding-bottom: 12px; }}
    h2   {{ color: #16213e; margin-top: 2em; }}
    h3   {{ color: #0f3460; }}
    code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
    pre  {{ background: #f4f4f4; padding: 16px; border-radius: 6px; overflow-x: auto; }}
    blockquote {{ border-left: 4px solid #ccc; margin: 0; padding-left: 16px; color: #555; }}
    .footer {{ margin-top: 48px; padding-top: 16px; border-top: 1px solid #e8e8e8;
               font-size: 0.85em; color: #888; }}
  </style>
</head>
<body>
{body}
<div class="footer">
  Generated by Deep Research · Powered by Claude, Gemini &amp; GPT-4o
</div>
</body>
</html>"""


def _markdown_to_html(markdown_text: str, title: str) -> str:
    body_html = md_lib.markdown(
        markdown_text,
        extensions=["extra", "codehilite", "toc"],
    )
    return _HTML_WRAPPER.format(title=title, body=body_html)


def send_report(to_email: str, query: str, markdown_report: str) -> bool:
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail, Content

        subject = f"Deep Research Report: {query[:80]}{'…' if len(query) > 80 else ''}"
        html_body = _markdown_to_html(markdown_report, title=subject)

        # FIX: Mail() html_content expects a plain string, not a Content object.
        # Set content list directly so both plain-text and HTML parts are included
        # in the correct MIME order (plain must come before html).
        message = Mail(
            from_email=(settings.sendgrid_from_email, settings.sendgrid_from_name),
            to_emails=to_email,
            subject=subject,
        )
        message.content = [
            Content("text/plain", markdown_report),
            Content("text/html", html_body),
        ]

        sg = SendGridAPIClient(settings.sendgrid_api_key)
        response = sg.send(message)

        if response.status_code in (200, 202):
            logger.info("Report emailed to %s (status %s)", to_email, response.status_code)
            return True

        logger.error("SendGrid status %s body: %s", response.status_code, response.body)
        return False

    except Exception as exc:
        logger.error("Failed to send email to %s: %s", to_email, exc, exc_info=True)
        return False